### ISSUE TITLE
[BUG] File left open after call to unihtml.NewDocument

### ISSUE THREAD

**Issue by radnams** [unidoc/unihtml#9] opened 2023-03-06 21:36 UTC
## Description
Im writing HTML to a temporary local file then loading that via unihtml.NewDocument() but after successfully creating a PDF from that HTML file and leaving that function, I'm unable to delete that temporary file straight away via os.Remove(). It's only after some time that the file lock is released (perhaps when GC cleans up?) that I can then delete the file.

## Expected Behavior
I would like to be able to delete the file that is used by unihtml.NewDocument() after I'm done using it or a way to explictly Close() the unihtml.Document() returned from it

## Actual Behavior
This is the code I'm running to generate the PDF from the HTML file.

```go
func createPdfFromHtml(htmlPath string) ([]byte, error) {

        // Load the html document from disk
	htmlDocument, err := unihtml.NewDocument(htmlPath)
	if err != nil {
		return nil, fmt.Errorf("html document error: %v\n", err)
	}

	// Make a new pdf creator
	c := creator.New()

	// Draw the html document
	if err = c.Draw(htmlDocument); err != nil {
		return nil, fmt.Errorf("draw error: %v\n", err)
	}

	// Write creator output to memory and return the bytes
	// rather than write to disk
	var b bytes.Buffer
	buf := bufio.NewWriter(&b)

	err = c.Write(buf)
	if err != nil {
		return nil, fmt.Errorf("write error: %v\n", err)
	}

	return b.Bytes(), nil
}
```

Following a call to this I attempt to delete the HTML file via os.Remove(htmlPath) but it can fail with:-

```The process cannot access the file because it is being used by another process.```

**Comment by sampila** [comment] 2024-06-21 15:01
Hi @radnams,

We are tried but unable to reproduce the issue, could you share code snippet to reproduce this issue for further investigation?

Best,
Alip

**Comment by ahall** [comment] 2024-08-13 14:52
Closing until we get a reproducable case.

**Closed as completed by ahall** 2024-08-13 14:52 UTC
